// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_render.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/timer/[name].tsx";
import * as $3 from "./routes/timer/edit/[name].tsx";
import * as $4 from "./routes/timer/new.tsx";
import * as $$0 from "./islands/CountDown.tsx";

const manifest = {
  routes: {
    "./routes/_render.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/timer/[name].tsx": $2,
    "./routes/timer/edit/[name].tsx": $3,
    "./routes/timer/new.tsx": $4,
  },
  islands: {
    "./islands/CountDown.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
